# Permalinks
permalink:           /blog/:title/

# Setup
title:               小米
tagline:             关于我的一切
url:                 https://dwjamie.github.io
paginate:            10
paginate_path:       /blog/page:num/
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              杰米
  url:               https://dwjamie.github.io
  email:             jamiecao3@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
